services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./scripts/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      - MONGO_INITDB_DATABASE-$MONGO_DATABASE
